services:

  mihomo_proxy_pool:
    build: .
    image: mihomo-proxy-pool
    container_name: mihomo-proxy-pool
    network_mode: host
    working_dir: /app
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
